### ISSUE TITLE
Swap absolute paths to relative paths

### ISSUE THREAD

**Issue by trvrb** [blab/h5n1-cambodia#1]
@lmoncla ---

Currently, the `.ipynb` figures have hardcoded absolute paths like `/Users/lmoncla/src/h5n1-cambodia/data/tree-jsons/flu_avian_h5n1_pb2_tree.json` (https://github.com/blab/h5n1-cambodia/blob/master/figures/figure-1-and-S2-plot-trees-with-baltic.ipynb?short_path=726132c#L132). This should be replaced with `../data/tree-jsons/flu_avian_h5n1_pb2_tree.json`. As it stands, I (and others) can't run these notebooks without modifying a very large number of absolute paths.

**Comment by lmoncla** [comment]
These have all been replaced with absolute paths, and should now work.
