### ISSUE TITLE
BALTIC as dependency

### ISSUE THREAD

**Issue by trvrb** [blab/h5n1-cambodia#2]
@lmoncla ---

In my brief testing, it looked like the `baltic.py` that's included at the most recent commit of https://github.com/evogytis/baltic is not compatible with the included `.ipynb`s. Can you test this? If this is indeed the case, I'd recommend just versioning your working version of `baltic.py` in this repo under `baltic/baltic.py`. (We really need to get BALTIC on PyPI. It's easy to do.)

**Comment by lmoncla** [comment]
Thanks for testing this. I reinstalled baltic from https://github.com/evogytis/baltic and it seemed to work ok for me. I added a working version into the repo, updated the README and paths, and have also added an environment file and instructions for creating the environment. This should hopefully solve these issues.
